language: python
python:
  - "3.4"
  - "3.5"
install: 
  - pip install -r requirements.txt
  - pip install mysqlclient
before_install:
  - sudo apt-get install -y libmysqlclient-dev
sudo: true
services:
  - mysql
before_script:
  - mysqladmin -u root password D120d10k83
  - mysql -e 'create database meraki_db;'
after_success:
  - python test_json.py
  - mysql -e 'INSERT INTO meraki_db.role (rolename) VALUES ('admin');INSERT INTO meraki_db.role (rolename) VALUES ('user');'
script: nosetests
